### ISSUE TITLE
Missing Libraries in Decompy Package: No decompy.robust_svd Function Found

### ISSUE THREAD

**Issue by Amitkupadhyay0** [subroy13/decompy#1]
I recently installed the Decompy package in my Anaconda environment in Windows 11. However, upon exploring the package, I discovered that there are no libraries available, and notably, decompy.robust_svd was missing entirely.
![issue_decompy](https://github.com/subroy13/decompy/assets/138156948/bdcd846a-7674-4808-b046-edc6fb6e20eb)
![issue_decompy](https://github.com/subroy13/decompy/assets/138156948/a1d1366f-5842-4889-a9cf-7f4f08d508cd)

**Comment by subroy13** [comment]
@Amitkupadhyay0 thanks for pointing it out. Turns out the following code block works.
```
from decompy.robust_svd import DensityPowerDivergence
```

I will shortly update the `Readme.md` with the correct example usage.
